In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('numpy-array-operations')
jovian.set_colab_id('1eus8T9L8BoJgN9Iv7DRDrSaj4YtKyodw')

> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>



# Python's Numpy Library: Notable functions


### More to the `import numpy as np`


- argsort() - creates matrix with the ordered indicies of values from input matrix
- dot() - calculates dot product of two matricies
- random.seed() - stores a pseudo-random state as a seed for reuse or replication
- std() - calculates standard deviation of input matrix
- linspace() - creates matrix from start and end point with size based on selected equal spacing between values 

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [ ]:
!pip install jovian --upgrade -q

In [ ]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "porkdown/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/porkdown/numpy-array-operations


'https://jovian.ml/porkdown/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [ ]:
import numpy as np

# List of functions explained 
`
function1 = np.argsort()
function2 = np.dot()
function3 = np.random.seed()
function4 = np.std()
function5 = np.linspace()
`

## Function 1 - np.argsort()

Returns the indicies that would sort an array, default by row

In [ ]:
# Example 1 - working 
arr1 = [[1, 2], 
        [3, 4.]]

np.argsort(arr1, axis=1)

array([[0, 1],
       [0, 1]])

Indicies of output matrix rank the order of values from the input matrix. axis=1, read horizontally

In [ ]:
# Example 2 - working
arr2 = [[5, 6, 7], 
        [8, 9, 10]]
np.argsort(arr2, axis=0)

array([[0, 0, 0],
       [1, 1, 1]])

Indicies of output matrix rank the order of values from the input matrix. axis=0, read vertically

In [ ]:
# Example 3 - trivial case
arr1 = [[[]]]
np.argsort(arr1)

array([], shape=(1, 1, 0), dtype=int64)

Works on multidimensional matricies, however input some data with the matching data type.

If strings are inputted as data, the fucntion will return 0 matrix which is inelegant.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "porkdown/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/porkdown/numpy-array-operations


'https://jovian.ml/porkdown/numpy-array-operations'

## Function 2 - dot()

Matrix multiplication

In [ ]:
# Example 1 - working
arr1 = [[1, 2], 
        [3, 4.]]
arr2 = [[5, 6, 7], 
        [8, 9, 10]]
result = np.dot(arr1,arr2)
result

array([[21., 24., 27.],
       [47., 54., 61.]])

Matrix multiplication arr1 by arr2, that exact order

In [ ]:
# Example 2 - working
arr1 = [[1, 2], 
        [3, 4.]]
identity_2 = np.eye(2)
result = np.dot(arr1,identity_2)
result

array([[1., 2.],
       [3., 4.]])

Matric multiplication arr1 by identity matrix 2x2. By property, result would be arr1.

In [ ]:
# Example 3 - breaking 
arr1 = [[1, 2], 
        [3, 4.]]
arr2 = [[5, 6, 7], 
        [8, 9, 10]]
np.dot(arr2,arr1)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

Dot product is not always communitive. Consider transposing to match dimensionality. Think inner match, return outer.

Check you dimensions when calculating dot product.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "porkdown/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/porkdown/numpy-array-operations


'https://jovian.ml/porkdown/numpy-array-operations'

## Function 3 - random.seed()

Save a generated pseudo-random matrix for use or replication 

In [ ]:
# Example 1 - working
np.random.seed(seed = 1)
random_array_1 = np.random.randint(10, size = (3,3))
random_array_1

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

The numbers are random but if you keep running the cell, the numbers won't change. It is stored in seed 1.

In [ ]:
# Example 2 - working
np.random.seed(seed = 9999)
random_array_1 = np.random.randint(100, size = (10,3))
random_array_1

array([[86, 47, 54],
       [92, 37, 25],
       [24, 16, 76],
       [33, 46, 69],
       [51, 33, 96],
       [79, 38, 36],
       [59, 20, 12],
       [22,  8, 28],
       [68, 45, 14],
       [39, 43,  9]])

Same idea as above, plenty of seeds to work with.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
np.random.seed(seed = -1)
random_array_1 = np.random.randint(10, size = (3,3))
random_array_1

ValueError: Seed must be between 0 and 2**32 - 1

Seed values have to be 32 bit unsigned integers so 0 to 2$**$32 - 1

Pick the right seed number.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "porkdown/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/porkdown/numpy-array-operations


'https://jovian.ml/porkdown/numpy-array-operations'

## Function 4 - std()

Calculate standard deviation of values in matrix

In [ ]:
# Example 1 - working
random_array_1 = np.random.randint(10000, size = (3,3,3))
print(random_array_1)
np.std(random_array_1)

[[[5393 5073 2754]
  [7176 2595  682]
  [1754 5595 8793]]

 [[3290 1315 5752]
  [1095 1043  720]
  [9969 4269 6734]]

 [[9373 5459 7349]
  [7362 2452 2439]
  [1441 6969 7912]]]


2846.6466561878

std = sqrt(mean(abs(x - x.mean())$**$2))

In [ ]:
# Example 2 - working
random_array_1 = np.random.randint(10000, size = (3,3,3))
print(random_array_1)
print("std: ",np.std(random_array_1))
print((np.std(random_array_1))**2)
print("var: ", np.var(random_array_1))

[[[6299 4976 5606]
  [7551  755 5719]
  [5103 8989 4469]]

 [[1140 1609 7480]
  [ 544  302  208]
  [4905 3453 6111]]

 [[2606 4026 3453]
  [ 445  709 2439]
  [1278 1335 6810]]]
std:  2581.3004814594888
6663112.175582988
var:  6663112.175582989


Same idea as above. Stanard deviation is the square root of the variance.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
array_1 = np.array([])
np.std(array_1)

nan

Put data in there. 

Use this to measrue the spread of data.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "porkdown/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/porkdown/numpy-array-operations


'https://jovian.ml/porkdown/numpy-array-operations'

## Function 5 - linspace()

Return evenly spaced numbers on a specified interval

In [ ]:
# Example 1 - working
vector = np.linspace(0,10000,5)
vector

array([    0.,  2500.,  5000.,  7500., 10000.])

Array from start 0 to end 10000 in 5 even intervals

In [ ]:
# Example 2 - working
vector = np.linspace(0,5,100)
vector

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

Array from start 0 to end 5 in 100 even intervals

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
vector = np.linspace(1,1,-1)
vector

ValueError: Number of samples, -1, must be non-negative.

Start 1 and end 1 is fine but the number of evenly spaced intervals must be non negative. Number of samples as 0 returns an empty array.

Start does not need to be lower than the end. That would just reverse the order.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "porkdown/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/porkdown/numpy-array-operations


'https://jovian.ml/porkdown/numpy-array-operations'