In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('01-tensor-operations')
jovian.set_colab_id('1eKRLRxYJWgiRGIID23_vLGuAVlDmFoyd')

# Exploring Five Pytorch Tensor Operations

An short introduction about PyTorch and about the chosen functions. 

- torch.eig()
- torch.where()
- torch.erfc()
- torch.lstsq()
- torch.det()

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.eig()

Computes the eigenvalues and the eigenvectors of a matrix

In [ ]:
# Example 1 - working (change this)
A = torch.tensor([[1, 2], [3, 4.]])
print(A)
Lambda, Nu = A.eig()
print(Lambda)
print(Nu)

tensor([[1., 2.],
        [3., 4.]])
tensor([[-0.3723,  0.0000],
        [ 5.3723,  0.0000]])
tensor([])


Since the tensor.eig() defaults the eigenvector calculation to False, meaning it will not compute it, we see nothing for Nu.

In [ ]:
# Example 2 - working
A = torch.tensor([[1, 2], [3, 4.]])
print(A)
Lambda, Nu = A.eig(eigenvectors = True)
print(Lambda)
print(Nu)

tensor([[1., 2.],
        [3., 4.]])
tensor([[-0.3723,  0.0000],
        [ 5.3723,  0.0000]])
tensor([[-0.8246, -0.4160],
        [ 0.5658, -0.9094]])


Here, the eigenvectors are computed.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
A = torch.tensor([[1., 2, 3], [3, 4, 5]])
print(A)
Lambda, Nu = A.eig(eigenvectors = True)
print(Lambda)
print(Nu)

tensor([[1., 2., 3.],
        [3., 4., 5.]])


RuntimeError: invalid argument 1: A should be square at /pytorch/aten/src/TH/generic/THTensorLapack.cpp:207

The matrix above is not a square matrix so the function will return an error.

Only use this function as it is defined mathematically, for square matricies.

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "porkdown/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/porkdown/01-tensor-operations


'https://jovian.ai/porkdown/01-tensor-operations'

## Function 2 - torch.where()

Returns a tensor with elements that satisfy the condition. Use value from X if condition evaluates to True, Y otherwise.

In [ ]:
# Example 1 - working
A = torch.randn(3,3)
B = torch.zeros(3,3)
result = torch.where(A > 0, A, B)
print("A: \n", A)
print("B: \n", B)
print("\nOutput: \n", result)

A: 
 tensor([[ 0.8334,  1.8895,  2.9877],
        [ 0.5832, -0.1007,  0.3932],
        [-0.9117,  0.4375,  0.4649]])
B: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Output: 
 tensor([[0.8334, 1.8895, 2.9877],
        [0.5832, 0.0000, 0.3932],
        [0.0000, 0.4375, 0.4649]])


Matrix A is normally distributed 3x3 matrix and the condition checks if values in A are positive. When the values are negative, values are replaced with that of matrix Y, which is a zero matrix of the same size.

In [ ]:
# Example 2 - working
A = torch.randn(3,3)
B = torch.zeros(3,3)
result = torch.where(A < -0.5, B, A)
print("A: \n", A)
print("B: \n", B)
print("\nOutput:\n", result)

A: 
 tensor([[ 0.5629, -0.2180, -0.5764],
        [ 0.0218, -0.3087,  1.3549],
        [-2.3364, -1.1738,  0.5426]])
B: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Output:
 tensor([[ 0.5629, -0.2180,  0.0000],
        [ 0.0218, -0.3087,  1.3549],
        [ 0.0000,  0.0000,  0.5426]])


Same idea here but Y matrix values where the condition evaluates to True.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
A = torch.randn(2,2)
B = torch.zeros(4,4)
result = torch.where(A < 0, B, A)
print("A: \n", A)
print("\nOutput:\n", result)

RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1

The two input matricies must be the same size otherwise mapping the values to insert when True or False will not work.

This function is a way to filter matricies but the inputs must be the same size.

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "porkdown/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/porkdown/01-tensor-operations


'https://jovian.ai/porkdown/01-tensor-operations'

## Function 3 - torch.erfc()

Computes complementary error function (1 - erf(x))

In [ ]:
# Example 1 - working
X = torch.randn(3,3)
print("X:\n", X)
erfc = torch.erfc(X)
print("\nerfc(X):\n", erfc)

X:
 tensor([[ 0.6861,  1.1032,  1.1077],
        [ 0.4807,  0.0567, -1.0033],
        [-1.6175, -0.7025, -0.5303]])

erfc(X):
 tensor([[0.3319, 0.1187, 0.1172],
        [0.4966, 0.9361, 1.8440],
        [1.9778, 1.6795, 1.5467]])


Complementary error function of X, a 3x3 matrix

In [ ]:
# Example 2 - working
X = torch.randn(1,1)
print("X:\n", X)
erfc = torch.erfc(X)
print("\nerfc(X):\n", erfc)

X:
 tensor([[1.9687]])

erfc(X):
 tensor([[0.0054]])


Complementary error function of X, a 1x1 matrix

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
X = torch.randn(3,3)
print("X:\n", X)
torch.erfc(input = X, output = nada)
print("\nerfc(X):\n", erfc)

X:
 tensor([[-0.0551, -0.1263, -1.0974],
        [-0.9892,  0.8563, -1.1869],
        [-0.1471, -0.3958, -0.3781]])


NameError: name 'nada' is not defined

If there is no output defined, don't bother to include it. You can set the result equal to a variable

"It is what it is."

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "porkdown/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/porkdown/01-tensor-operations


'https://jovian.ai/porkdown/01-tensor-operations'

## Function 4 - torch.lstsq()

Computes least squares for input matrix X of size (m×k) and a matrix Y of size (m×n)

In [ ]:
# Example 1 - working
X = torch.randn(3,3)
Y = torch.randn(3,3)

n = Y.shape[1]
solution, QR = torch.lstsq(X, Y)
print("X:\n",X)
print("Y:\n",Y)
print("Least Squares Solution:\n", solution[:n,:])
print("\nY @ solution = \n", Y@solution[:n,:])
print("\nX approximation:\n", X)

X:
 tensor([[ 0.2898,  2.1879,  0.3539],
        [-0.5671, -0.8776,  1.2212],
        [ 0.1993, -0.1486, -0.6420]])
Y:
 tensor([[-0.6785,  1.1009,  0.5156],
        [-0.9456,  2.8298, -0.0274],
        [-0.2919, -0.0872,  2.1026]])
Least Squares Solution:
 tensor([[ -2.0191, -11.1756,  -0.1311],
        [ -0.8772,  -4.0618,   0.3848],
        [ -0.2219,  -1.7908,  -0.3076]])

Y @ solution = 
 tensor([[ 0.2898,  2.1879,  0.3539],
        [-0.5671, -0.8776,  1.2212],
        [ 0.1993, -0.1486, -0.6420]])

X approximation:
 tensor([[ 0.2898,  2.1879,  0.3539],
        [-0.5671, -0.8776,  1.2212],
        [ 0.1993, -0.1486, -0.6420]])


Y by least squares solution is an approximation of X

In [ ]:
# Example 2 - working
X = torch.randn(3,3)
Y = torch.randn(3,3)

n = Y.shape[1]
solution, QR = torch.lstsq(X, Y)
print("Least Squares Solution:\n", solution[:n,:])
print("\nQR:\n", QR)

Least Squares Solution:
 tensor([[ -0.2350,   0.0374,   0.1235],
        [  2.7765,  -9.2675,   2.4876],
        [  3.0747, -11.4242,   3.4261]])

QR:
 tensor([[-2.4768,  0.0491,  0.1372],
        [ 0.2182,  1.5951, -1.3383],
        [-0.6949, -0.4701,  0.1677]])


Least Squares solution and QR factorization.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
X = torch.randn(3,3)
Y = torch.randn(4,3)

n = Y.shape[1]
solution, QR = torch.lstsq(X, Y)
print("Least Squares Solution:\n", solution[:n,:])
print("\nQR:\n", QR)

RuntimeError: Expected A and b to have same size at dim 0, but A has 4 rows and B has 3 rows

Number of rows must match

This function is typically used to get weights in linear regression.

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

## Function 5 - torch.det()

Computes the determinant of a sqaure matrix or groups of square matricies

In [ ]:
# Example 1 - working
A = torch.tensor([[1.,0],[0,1]])
print(A)
print('det(A):')
torch.det(A)

tensor([[1., 0.],
        [0., 1.]])
det(A):


tensor(1.)

The determinant of a 2x2 Identity matrix is 1.

In [ ]:
# Example 2 - working
A = torch.randn(2, 2, 2, 2)
print(A)
print('det(A):')
torch.det(A)

tensor([[[[-1.0329, -0.3397],
          [-1.7874, -0.5596]],

         [[-0.8990,  1.7743],
          [ 0.2428, -0.6517]]],


        [[[ 0.4628,  0.8481],
          [-0.3221,  0.3541]],

         [[-1.2001, -0.5225],
          [-0.8416, -0.8502]]]])
det(A):


tensor([[-0.0293,  0.1550],
        [ 0.4370,  0.5805]])

Determinants of four matricies

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
A = torch.tensor([[1, 1, 1], [1, 1, 1]])
torch.det(A)

RuntimeError: A must be batches of square matrices, but they are 3 by 2 matrices

The matrix above is not a square matrix so there is no determinant.

Only use this function as it is defined mathematically, for square matricies.

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "porkdown/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/porkdown/01-tensor-operations


'https://jovian.ai/porkdown/01-tensor-operations'

## Conclusion

This notebook covered five basic Pytorch tensor functions. More information can be found on the Pytorch documentation.

## Reference Links
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "porkdown/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/porkdown/01-tensor-operations


'https://jovian.ai/porkdown/01-tensor-operations'